version: '3.8'

services:
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: hotnews-backend
    volumes:
      - ./Server:/app
      - /app/node_modules
    ports:
      - "5556:5556"
    env_file:
      - ./Server/.env
    restart: always

  frontend:
    build:
      context: ./Hot-News/hot-news-app
      dockerfile: Dockerfile
    container_name: hotnews-frontend
    ports:
      - "5555:8080"
    depends_on:
      - backend
    restart: always

networks:
  default:
    name: hotnews-network 